@startuml
'https://plantuml.com/class-diagram

note top of Reporter : sendReport should be split up between Server and Reporter
class Reporter {
sendReport()
addReport()
clearReports()
addNewLines()
}


@enduml